name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - main

jobs:
  Continuous-Integration:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you want to use

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '7' # You can specify the pnpm version you want here

      - name: Install Dependencies
        run: pnpm install

      - name: Run linting check
        run: pnpm run lint:check

      - name: Check formatting
        run: pnpm run format:check

      - name: Fix formatting
        run: pnpm run format:fix
